# Generated by Django 3.2 on 2021-12-25 05:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_icon', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('package_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.PositiveIntegerField()),
                ('package_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('shop_name', models.CharField(max_length=255, unique=True)),
                ('shop_address1', models.TextField(blank=True, null=True)),
                ('shop_address2', models.TextField(blank=True, null=True)),
                ('shop_contact', models.CharField(max_length=255, null=True)),
                ('shop_bin_no', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_vat', models.CharField(blank=True, max_length=255, null=True)),
                ('mushak_no', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_logo', models.ImageField(null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('vat_amount', models.FloatField(default=0, null=True)),
                ('show_mushak', models.BooleanField(default=False, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PackageCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bkash_number', models.CharField(blank=True, max_length=16, null=True)),
                ('bkash_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nagad_number', models.CharField(blank=True, max_length=16, null=True)),
                ('nagad_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False, null=True)),
                ('customer_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.package')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SAAS.shop')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
