# Generated by Django 3.2 on 2022-01-08 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_item_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restcheckout',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
